name: video_player_web_hls
description: Web platform implementation of video_player and supports hls on chrome and other browsers.
homepage: https://github.com/balvinderz/video_player_web_hls
# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.1.6

flutter:
  plugin:
    platforms:
      web:
        pluginClass: VideoPlayerPluginHls 
        fileName: video_player_web_hls.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  video_player_platform_interface: ^2.0.0
  js: ^0.6.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"